In [3]:
import os
import pandas as pd
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas
from dotenv import load_dotenv

In [4]:
load_dotenv()

# --- 1. SET UP YOUR SNOWFLAKE CREDENTIALS ---
conn = snowflake.connector.connect(
    user=os.getenv('SNOWFLAKE_USER'),
    password=os.getenv('SNOWFLAKE_PASSWORD'),
    account=os.getenv('SNOWFLAKE_ACCOUNT'),
    warehouse=os.getenv('SNOWFLAKE_WAREHOUSE'),
    database=os.getenv('SNOWFLAKE_DATABASE'),
    schema=os.getenv('SNOWFLAKE_SCHEMA'),
    role=os.getenv('SNOWFLAKE_ROLE')
)

# if this column is null, does it break or bias any analysis I'm planning?

In [5]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(order_id) AS order_id_present,
    COUNT(customer_id) AS customer_id_present,
    ROUND(100.0 * COUNT(customer_id) / COUNT(*), 2) AS customer_id_pct,
    COUNT(order_date) AS order_date_present,
    COUNT(approval_date) AS approval_date_present,
    COUNT(shipped_date) AS shipped_date_present,
    COUNT(delivered_date) AS delivered_date_present,
    COUNT(estimated_delivery_date) AS est_delivery_present,
    COUNT(order_status) AS order_status_present,
    COUNT(seller_id) AS seller_id_present,
    COUNT(carrier) AS carrier_present,
    COUNT(warehouse_origin) AS warehouse_origin_present,
    COUNT(num_items) AS num_items_present,
    COUNT(order_total) AS order_total_present,
    COUNT(shipping_cost) AS shipping_cost_present,
    COUNT(order_channel) AS order_channel_present,
    COUNT_IF(delivered_date < order_date) AS impossible_dates
FROM sales_raw."01_ORDERS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\1941562640.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,ORDER_ID_PRESENT,CUSTOMER_ID_PRESENT,CUSTOMER_ID_PCT,ORDER_DATE_PRESENT,APPROVAL_DATE_PRESENT,SHIPPED_DATE_PRESENT,DELIVERED_DATE_PRESENT,EST_DELIVERY_PRESENT,ORDER_STATUS_PRESENT,SELLER_ID_PRESENT,CARRIER_PRESENT,WAREHOUSE_ORIGIN_PRESENT,NUM_ITEMS_PRESENT,ORDER_TOTAL_PRESENT,SHIPPING_COST_PRESENT,ORDER_CHANNEL_PRESENT,IMPOSSIBLE_DATES
0,15000,15000,14707,98.05,15000,14625,14321,14009,14625,15000,15000,15000,15000,15000,15000,15000,15000,130

In [6]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(order_item_id) AS order_item_id_present,
    COUNT(order_id) AS order_id_present,
    ROUND(100.0 * COUNT(order_id) / COUNT(*), 2) AS order_id_pct,
    COUNT(product_id) AS product_id_present,
    ROUND(100.0 * COUNT(product_id) / COUNT(*), 2) AS product_id_pct,
    COUNT(seller_id) AS seller_id_present,
    ROUND(100.0 * COUNT(seller_id) / COUNT(*), 2) AS seller_id_pct,
    COUNT(quantity) AS quantity_present,
    COUNT(unit_price) AS unit_price_present,
    COUNT(discount_pct) AS discount_pct_present,
    COUNT(item_total) AS item_total_present,
    COUNT(item_weight_kg) AS item_weight_kg_present
FROM sales_raw."02_ORDER_ITEMS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\1217348074.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,ORDER_ITEM_ID_PRESENT,ORDER_ID_PRESENT,ORDER_ID_PCT,PRODUCT_ID_PRESENT,PRODUCT_ID_PCT,SELLER_ID_PRESENT,SELLER_ID_PCT,QUANTITY_PRESENT,UNIT_PRICE_PRESENT,DISCOUNT_PCT_PRESENT,ITEM_TOTAL_PRESENT,ITEM_WEIGHT_KG_PRESENT
0,29668,29668,29668,100.0,29668,100.0,29668,100.0,29668,29668,29668,29668,29668

In [7]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(product_id) AS product_id_present,
    COUNT(product_name) AS product_name_present,
    COUNT(category) AS category_present,
    COUNT(subcategory) AS subcategory_present,
    COUNT(price) AS price_present,
    COUNT(cost_price) AS cost_price_present,
    COUNT(weight_kg) AS weight_kg_present,
    COUNT(length_cm) AS length_cm_present,
    COUNT(width_cm) AS width_cm_present,
    COUNT(height_cm) AS height_cm_present
FROM sales_raw."03_PRODUCTS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\3244249518.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,PRODUCT_ID_PRESENT,PRODUCT_NAME_PRESENT,CATEGORY_PRESENT,SUBCATEGORY_PRESENT,PRICE_PRESENT,COST_PRICE_PRESENT,WEIGHT_KG_PRESENT,LENGTH_CM_PRESENT,WIDTH_CM_PRESENT,HEIGHT_CM_PRESENT
0,480,480,480,480,480,480,480,480,480,480,480

In [8]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(customer_id) AS customer_id_present,
    ROUND(100.0 * COUNT(customer_id) / COUNT(*), 2) AS customer_id_pct,
    COUNT(customer_segment) AS customer_segment_present,
    COUNT(acquisition_channel) AS acquisition_channel_present,
    COUNT(signup_date) AS signup_date_present,
    COUNT(city) AS city_present,
    COUNT(region) AS region_present,
    COUNT(zip_code) AS zip_code_present
FROM sales_raw."04_CUSTOMERS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\2838602491.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,CUSTOMER_ID_PRESENT,CUSTOMER_ID_PCT,CUSTOMER_SEGMENT_PRESENT,ACQUISITION_CHANNEL_PRESENT,SIGNUP_DATE_PRESENT,CITY_PRESENT,REGION_PRESENT,ZIP_CODE_PRESENT
0,6200,6200,100.0,6200,6200,6200,6200,6200,6200

In [9]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(seller_id) AS seller_id_present,
    COUNT(seller_name) AS seller_name_present,
    COUNT(warehouse_location) AS warehouse_location_present,
    COUNT(fulfillment_type) AS fulfillment_type_present,
    COUNT(quality_score) AS quality_score_present,
    COUNT(city) AS city_present,
    COUNT(state) AS state_present
FROM sales_raw."05_SELLERS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\533064870.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,SELLER_ID_PRESENT,SELLER_NAME_PRESENT,WAREHOUSE_LOCATION_PRESENT,FULFILLMENT_TYPE_PRESENT,QUALITY_SCORE_PRESENT,CITY_PRESENT,STATE_PRESENT
0,45,45,45,45,45,45,45,45

In [10]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(event_id) AS event_id_present,
    COUNT(order_id) AS order_id_present,
    ROUND(100.0 * COUNT(order_id) / COUNT(*), 2) AS order_id_pct,
    COUNT(carrier) AS carrier_present,
    COUNT(warehouse_origin) AS warehouse_origin_present,
    COUNT(event_type) AS event_type_present,
    COUNT(event_timestamp) AS event_timestamp_present,
    COUNT(event_sequence) AS event_sequence_present
FROM sales_raw."06_SHIPPING_LOGISTICS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\1442567465.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,EVENT_ID_PRESENT,ORDER_ID_PRESENT,ORDER_ID_PCT,CARRIER_PRESENT,WAREHOUSE_ORIGIN_PRESENT,EVENT_TYPE_PRESENT,EVENT_TIMESTAMP_PRESENT,EVENT_SEQUENCE_PRESENT
0,91850,91850,91850,100.0,91850,91850,91850,90930,91850

In [11]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(return_id) AS return_id_present,
    COUNT(order_id) AS order_id_present,
    ROUND(100.0 * COUNT(order_id) / COUNT(*), 2) AS order_id_pct,
    COUNT(order_item_id) AS order_item_id_present,
    COUNT(product_id) AS product_id_present,
    COUNT(customer_id) AS customer_id_present,
    COUNT(return_initiated_date) AS return_initiated_date_present,
    COUNT(return_received_date) AS return_received_date_present,
    ROUND(100.0 * COUNT(return_received_date) / COUNT(*), 2) AS return_received_pct,
    COUNT(return_reason) AS return_reason_present,
    COUNT(refund_amount) AS refund_amount_present,
    COUNT(return_status) AS return_status_present
FROM sales_raw."07_RETURNS_CANCELLATIONS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\480121407.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,RETURN_ID_PRESENT,ORDER_ID_PRESENT,ORDER_ID_PCT,ORDER_ITEM_ID_PRESENT,PRODUCT_ID_PRESENT,CUSTOMER_ID_PRESENT,RETURN_INITIATED_DATE_PRESENT,RETURN_RECEIVED_DATE_PRESENT,RETURN_RECEIVED_PCT,RETURN_REASON_PRESENT,REFUND_AMOUNT_PRESENT,RETURN_STATUS_PRESENT
0,3187,3187,3187,100.0,3187,3187,3120,3187,2779,87.2,3187,3187,3187

In [12]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(review_id) AS review_id_present,
    COUNT(order_id) AS order_id_present,
    ROUND(100.0 * COUNT(order_id) / COUNT(*), 2) AS order_id_pct,
    COUNT(customer_id) AS customer_id_present,
    COUNT(product_id) AS product_id_present,
    COUNT(rating) AS rating_present,
    COUNT(review_date) AS review_date_present,
    COUNT(delivery_rating) AS delivery_rating_present,
    COUNT(product_rating) AS product_rating_present,
    COUNT(review_topics) AS review_topics_present
FROM sales_raw."08_CUSTOMER_REVIEWS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\653249430.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,REVIEW_ID_PRESENT,ORDER_ID_PRESENT,ORDER_ID_PCT,CUSTOMER_ID_PRESENT,PRODUCT_ID_PRESENT,RATING_PRESENT,REVIEW_DATE_PRESENT,DELIVERY_RATING_PRESENT,PRODUCT_RATING_PRESENT,REVIEW_TOPICS_PRESENT
0,8686,8686,8686,100.0,8532,8686,8686,8686,8686,8686,7073

In [13]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(snapshot_id) AS snapshot_id_present,
    COUNT(snapshot_date) AS snapshot_date_present,
    COUNT(product_id) AS product_id_present,
    COUNT(warehouse) AS warehouse_present,
    COUNT(quantity_on_hand) AS quantity_on_hand_present,
    COUNT(quantity_reserved) AS quantity_reserved_present,
    COUNT(quantity_available) AS quantity_available_present,
    COUNT(reorder_point) AS reorder_point_present,
    COUNT(is_stockout) AS is_stockout_present
FROM sales_raw."09_INVENTORY_SNAPSHOTS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\1137659626.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,SNAPSHOT_ID_PRESENT,SNAPSHOT_DATE_PRESENT,PRODUCT_ID_PRESENT,WAREHOUSE_PRESENT,QUANTITY_ON_HAND_PRESENT,QUANTITY_RESERVED_PRESENT,QUANTITY_AVAILABLE_PRESENT,REORDER_POINT_PRESENT,IS_STOCKOUT_PRESENT
0,8400,8400,8400,8400,8400,8400,8400,8400,8400,8400

In [14]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(campaign_id) AS campaign_id_present,
    COUNT(month) AS month_present,
    COUNT(channel) AS channel_present,
    COUNT(campaign_type) AS campaign_type_present,
    COUNT(spend) AS spend_present,
    COUNT(conversions) AS conversions_present,
    COUNT(revenue_attributed) AS revenue_attributed_present
FROM sales_raw."10_MARKETING_CAMPAIGNS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\636011751.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,CAMPAIGN_ID_PRESENT,MONTH_PRESENT,CHANNEL_PRESENT,CAMPAIGN_TYPE_PRESENT,SPEND_PRESENT,CONVERSIONS_PRESENT,REVENUE_ATTRIBUTED_PRESENT
0,240,240,240,240,240,240,240,240

In [15]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(ticket_id) AS ticket_id_present,
    COUNT(order_id) AS order_id_present,
    ROUND(100.0 * COUNT(order_id) / COUNT(*), 2) AS order_id_pct,
    COUNT(customer_id) AS customer_id_present,
    COUNT(created_date) AS created_date_present,
    COUNT(resolved_date) AS resolved_date_present,
    ROUND(100.0 * COUNT(resolved_date) / COUNT(*), 2) AS resolved_date_pct,
    COUNT(issue_type) AS issue_type_present,
    COUNT(status) AS status_present,
    COUNT(resolution_hours) AS resolution_hours_present,
    COUNT(channel) AS channel_present,
    COUNT(agent_id) AS agent_id_present
FROM sales_raw."11_SUPPORT_TICKETS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\3338656318.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,TICKET_ID_PRESENT,ORDER_ID_PRESENT,ORDER_ID_PCT,CUSTOMER_ID_PRESENT,CREATED_DATE_PRESENT,RESOLVED_DATE_PRESENT,RESOLVED_DATE_PCT,ISSUE_TYPE_PRESENT,STATUS_PRESENT,RESOLUTION_HOURS_PRESENT,CHANNEL_PRESENT,AGENT_ID_PRESENT
0,2250,2250,2250,100.0,2203,2250,1975,87.78,2250,2250,1975,2250,2250

In [16]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(cancellation_id) AS cancellation_id_present,
    COUNT(order_id) AS order_id_present,
    ROUND(100.0 * COUNT(order_id) / COUNT(*), 2) AS order_id_pct,
    COUNT(customer_id) AS customer_id_present,
    COUNT(cancellation_date) AS cancellation_date_present,
    COUNT(cancellation_reason) AS cancellation_reason_present,
    COUNT(was_order_total) AS was_order_total_present
FROM sales_raw."12_CANCELLATIONS";
"""

df = pd.read_sql(query, conn)
display(df)

C:\Users\frase\AppData\Local\Temp\ipykernel_14412\1963211043.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,TOTAL_ROWS,CANCELLATION_ID_PRESENT,ORDER_ID_PRESENT,ORDER_ID_PCT,CUSTOMER_ID_PRESENT,CANCELLATION_DATE_PRESENT,CANCELLATION_REASON_PRESENT,WAS_ORDER_TOTAL_PRESENT
0,375,375,375,100.0,361,375,375,375

In [17]:
conn.close()